[project]
name = "nonebot-plugin-reminder"
version = "0.1.0"
description = "use qq robots as a reminder"
readme = "README.md"
requires-python = ">=3.8, <4.0"


[tool.pyright]
venvPath = "/home/xac/Documents/test-plugins/"
venv = ".venv"

